### ISSUE TITLE
Save Image Now not working

### ISSUE THREAD

**Issue by aensaro** [gomita/firegestures#130]
I am using the latest version, with which this problem started to appear by the way.
The error appears when trying to Save Image Now:
`TypeError: aInitiatingDocument is null`

**Comment by spider1313** [comment]
for now you can add in options a script for you gesture with the following code:

----------
var srcNode = FireGestures.sourceNode;
// get the link URL inside the node
var linkURL = FireGestures.getLinkURL(srcNode);

if (srcNode.nodeType == Node.ELEMENT_NODE &&
    srcNode instanceof Components.interfaces.nsIImageLoadingContent && 
    srcNode.currentURI) 
{
  var docURL=srcNode.ownerDocument.location.href;
  var imageURL=srcNode.currentURI.spec;
  saveImageURL(imageURL, null, "SaveImageTitle", false, true, makeURI(docURL),document);
}
--------------------------------
the problem is in the call of saveimageurl, now needs 7th param, document

**Comment by gomita** [comment]
Fixed: 7a58fd986f18acb4c43a52c9de1be9f4fb77486a
